[package]
name = "aoc21"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
clap = "3.0.0-beta.5"
ansi_term = "0.12.1"

[dependencies.sdl2]
version = "0.35.1"
default-features = false
features = ["ttf","image","gfx"]
